name: Build and publish base images

on:
  workflow_dispatch: {}
  
  push:
    branches: [ main ]

  schedule:
    # Weekly on Tuesdays at 9am PST
    - cron: "0 17 * * 2"

jobs:
  build-and-publish-images:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        LISP_IMPLEMENTATION: ["sbcl", "allegro", "ccl"]

    env:
      ALLEGRO_LICENSE: ${{ secrets.ALLEGRO_LICENSE }}

    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and publish the Docker image
        run: |
               docker build ${{ matrix.LISP_IMPLEMENTATION }} --build-arg ALLEGRO_LICENSE --tag ghcr.io/coalton-lang/${{ matrix.LISP_IMPLEMENTATION }}-base:latest
               docker push ghcr.io/coalton-lang/${{ matrix.LISP_IMPLEMENTATION }}-base:latest
