name: Build base images

on:
  pull_request:
    branches: [ main ]

jobs:
  build-images:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        LISP_IMPLEMENTATION: ["sbcl", "ccl"]

    env:
      ALLEGRO_LICENSE: ${{ secrets.ALLEGRO_LICENSE }}

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
               docker build ${{ matrix.LISP_IMPLEMENTATION }} --build-arg ALLEGRO_LICENSE --tag ghcr.io/coalton-lang/${{ matrix.LISP_IMPLEMENTATION }}-base:latest
